spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/fac?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: ${SERVER_MODE}

server:
  servlet:
    context-path: /api

management:
  server:
    port: 8081
    base-path: /api
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: ${APPLICATION_NAME}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
jwt:
  accessTokenSecret: ${USER_ACCESS_TOKEN_SECRET}
  accessTokenExpire: ${USER_ACCESS_TOKEN_EXPIRE}
  refreshTokenSecret: ${USER_REFRESH_TOKEN_SECRET}
  refreshTokenExpire: ${USER_REFRESH_TOKEN_EXPIRE}