name: CI

on:
  push:
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      env:
        MYSQL_IP: ${{ secrets.MYSQL_IP }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        USER_ACCESS_TOKEN_SECRET: ${{ secrets.USER_ACCESS_TOKEN_SECRET }}
        USER_ACCESS_TOKEN_EXPIRE: ${{ secrets.USER_ACCESS_TOKEN_EXPIRE }}
        USER_REFRESH_TOKEN_SECRET: ${{ secrets.USER_REFRESH_TOKEN_SECRET }}
        USER_REFRESH_TOKEN_EXPIRE: ${{ secrets.USER_REFRESH_TOKEN_EXPIRE }}
      run: ./gradlew build --no-build-cache --rerun-tasks

    - name: Notify Discord about build result
      if: always()
      run: |
        STATUS="${{ job.status }}"
        if [ "$STATUS" == "success" ]; then
          MESSAGE="✅ Build succeeded!"
        else
          MESSAGE="❌ Build failed!"
        fi
        PR_NUMBER="${{ github.event.pull_request.number }}"
        PR_URL="${{ github.event.pull_request.html_url }}"
        curl -H "Content-Type:application/json" -d "{\"content\": \"$MESSAGE PR: #$PR_NUMBER ($PR_URL)\" }" ${{ secrets.DISCORD_WEBHOOK_URL }}

